---
title: MSSQLSERVER_26013 | Microsoft Docs
ms.custom: ''
ms.date: 04/04/2017
ms.prod: sql
ms.prod_service: database-engine
ms.component: errors-events
ms.reviewer: ''
ms.suite: sql
ms.technology: supportability
ms.tgt_pltfrm: ''
ms.topic: language-reference
helpviewer_keywords:
- 26013 (Database Engine error)
ms.assetid: 7362fca4-b005-4872-bdfa-a3e32f834db8
caps.latest.revision: 9
author: MashaMSFT
ms.author: mathoma
manager: craigg
ms.openlocfilehash: 0a302daab977d722d0732791a7463d0f2e737bf8
ms.sourcegitcommit: f1caaa156db2b16e817e0a3884394e7b30fb642f
ms.translationtype: HT
ms.contentlocale: ja-JP
ms.lasthandoff: 05/04/2018
---
# <a name="mssqlserver26013"></a>MSSQLSERVER_26013
[!INCLUDE[appliesto-ss-xxxx-xxxx-xxx-md](../../includes/appliesto-ss-xxxx-xxxx-xxx-md.md)]
  
## <a name="details"></a>詳細  
  
|||  
|-|-|  
|製品名|SQL Server|  
|イベント ID|26013|  
|イベント ソース|MSSQLSERVER|  
|コンポーネント|SQLEngine|  
|シンボル名|SNI_SSL_READY|  
|メッセージ テキスト|暗号化用の証明書 [Cert Hash(sha1) "%hs"] が正常に読み込まれました。|  
  
## <a name="explanation"></a>説明  
これは情報メッセージです。 名前付き証明書が [!INCLUDE[ssNoVersion](../../includes/ssnoversion-md.md)] に正常に読み込まれました。この証明書は暗号化に使用できます。  
  
## <a name="user-action"></a>ユーザーの操作  
必要なアクションはありません。  
  
